version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Nanoleaf-Plugin/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget"
    directory: "/NanoleafGUI-Plugin/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
